---
brew_taps:
  - FelixKratz/formulae
  - daipeihust/tap

brew_packages:
  - 1password-cli
  - awscli
  - bat
  - eza
  - fd
  - ffmpeg
  - ffmpegthumbnailer
  - fzf
  - gh
  - git
  - git-filter-repo
  - hatch
  - git-gui
  - httpie
  - imagemagick
  - im-select
  - jq
  - lazygit
  - lua
  - mysql
  - neovim
  - sevenzip
  - tree
  - poppler
  - powerlevel10k
  - ripgrep
  - thefuck
  - volta
  - yazi
  - zoxide
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting

brew_cask_packages:
  - 1password
  - alfred
  - alt-tab
  - antigravity
  - appcleaner
  - bartender
  - brave-browser
  - chatgpt-atlas
  - corretto@21
  - clickup
  - cron
  - dbeaver-community
  - docker
  - font-noto-sans-jp
  - font-noto-serif-jp
  - font-plemol-jp
  - font-plemol-jp-nf
  - ghostty
  - git-credential-manager
  - intellij-idea
  - karabiner-elements
  - keyboardcleantool
  - keyclu
  - menubarx
  - miro
  - monitorcontrol
  - mysqlworkbench
  - nikitabobko/tap/aerospace
  - notion
  - obsidian
  - pgadmin4
  - pycharm-ce
  - postman
  - session-manager-plugin
  - shottr
  - visual-studio-code
  - vlc
